version: '3.7'

services:
    api:
        build:
            target: dev
        depends_on:
            - db
        env_file:
            - docker-compose-api.env
        ports:
            - "$PORT:$PORT"
        volumes:
            - .:/www
            - /www/node_modules

    db:
        image: mongo
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - "27017:27017"

    swagger-editor:
        image: makst/swagger-editor-live-docker
        environment:
            - EDITOR_PORT=$SWAGGER_EDITOR_PORT
        volumes:
            - ./src/api/swagger.yml:/swagger.yml
        ports:
            - "$SWAGGER_EDITOR_PORT:$SWAGGER_EDITOR_PORT"
